apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../rbac-base
  - device_plugin_service_account.yaml
  - device_plugin_cluster_role.yaml
  - device_plugin_role_binding.yaml
  - module_loader_service_account.yaml
  - module_loader_cluster_role.yaml
  - module_loader_role_binding.yaml
  - role.yaml
